--- 
jobs: 
  analyze: 
    docker: 
      - 
        image: "circleci/node:13.8.0"
    steps: 
      - 
        run: "echo My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."
  build: 
    docker: 
      - 
        image: "cimg/base:2020.01"
    steps: 
      - checkout
      - 
        run: 
          command: echo $CircleCI_Env_Variable
          name: "echo an env var that is part of our project"
      - 
        run: "echo My pipeline git url is << pipeline.project.git_url >> and project type is << pipeline.project.type>>."
  test: 
    docker: 
      - 
        image: "circleci/node:13.8.0"
    steps: 
      - 
        run: "echo My pipeline.git.branch is << pipeline.git.branch >>"
version: 2.1
workflows: 
  CICD: 
    jobs: 
      - build
      - 
        test: 
          requires: 
            - build
      - 
        analyze: 
          requires: 
            - test
